[package]
name = "thesis_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.8"
memory-stats = "1.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
colored = "2"
# cli-clipboard = "0.4"